import Footer from "@/components/homepage/footer";
import Navbar from "@/components/homepage/navbar";
import { Toaster } from "sonner";

export const metadata = {
	title: "Homepage | Bakso Dono Reborn",
	description: "Generated by create next app",
	icons: {
		icon: "/favicon.ico",
	},
};

export default function HomeRoot({ children }) {
	return (
		<>
			<Toaster position="top-center" />
			<Navbar />
			{children}
			<Footer />
		</>
	);
}
