import React from "react";
import Footer from "@/components/homepage/footer";
import Navbar from "@/components/homepage/navbar";
import { Toaster } from "sonner";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import Image from "next/image";

export const metadata = {
	title: "Homepage | Bakso Dono Reborn",
	description: "Generated by create next app",
	icons: {
		icon: [
			{ url: "/favicon.ico", sizes: "any" },
			{ url: "/icon-192x192.png", sizes: "192x192", type: "image/png" },
			{ url: "/icon-512x512.png", sizes: "512x512", type: "image/png" },
		],
		apple: [{ url: "/icon-192x192.png", sizes: "180x180" }],
	},
	manifest: "/manifest.json",
};

export default function HomeRoot({ children }) {
	return (
		<div className="relative">
			<Toaster position="top-center" />
			<Navbar />
			{children}
			<Footer />
			<div className="fixed bottom-0 right-0 m-4">
				<Button asChild size="icon" variant="outline">
					<Link href={"https://wa.me/62895609977877"}>
						<Image src={"/wa.png"} width={32} height={32} alt="wa" />
					</Link>
				</Button>
			</div>
		</div>
	);
}
